"""
settings.py — Central configuration for AI Income Lab blog agent.
All sensitive values (API keys, blog ID) are loaded from environment
variables so they work both locally (.env file) and in GitHub Actions
(GitHub Secrets).
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── Gemini API ─────────────────────────────────────────────────────────────────
GEMINI_API_KEY   = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL     = "gemini-2.5-flash"
GEMINI_FALLBACK  = "gemini-2.0-flash"

# ── Blogger ────────────────────────────────────────────────────────────────────
BLOGGER_BLOG_ID  = os.getenv("BLOGGER_BLOG_ID", "")
BLOGGER_TOKEN_FILE = "token.json"           # generated by setup_auth.py

# ── Blog brand ─────────────────────────────────────────────────────────────────
# ── Blog brand ─────────────────────────────────────────────────────────────────
BLOG_NAME        = "TrendPulse Daily"
BLOG_TAGLINE     = "What the world is talking about — explained simply."
BLOG_AUTHOR      = "TrendPulse Editorial"

# ── Article generation & Staggered Schedule ──────────────────────────────────
# 3 runs/day with 1 article per run across 24h, weekly, and monthly horizons.
ARTICLES_PER_RUN = int(os.getenv("ARTICLES_COUNT", "1"))
MIN_WORD_COUNT   = 1200
MAX_WORD_COUNT   = 2000
GEMINI_TEMPERATURE = 0.75

# Slot Archetypes matching time horizons (IST = UTC + 5:30)
# Morning (03:30 UTC / 9:00 AM IST)  -> 24-Hour Real-Time Pulse (Breaking & Fresh)
# Noon    (08:30 UTC / 2:00 PM IST)  -> Weekly Momentum Teardown (How-To & Guides)
# Evening (14:30 UTC / 8:00 PM IST)  -> Monthly Big Picture (Deep Explainer & Culture)
SLOT_CONFIGS = {
    "morning": {
        "name": "24-Hour Trend Pulse",
        "format": "market_breakdown",
        "horizon": "24h",
        "niche_preference": "tech_innovation",
        "primary_color": "#2563eb",   # Electric Cobalt Blue
        "bg_gradient": "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #1e3a8a 100%)",
        "badge_bg": "#2563eb",
    },
    "noon": {
        "name": "Weekly Deep Dive & Teardown",
        "format": "how_to",
        "horizon": "week",
        "niche_preference": "business_money",
        "primary_color": "#059669",   # Mint Emerald
        "bg_gradient": "linear-gradient(135deg, #064e3b 0%, #065f46 50%, #047857 100%)",
        "badge_bg": "#059669",
    },
    "evening": {
        "name": "Big Picture Explainer & Future",
        "format": "case_study",
        "horizon": "month",
        "niche_preference": "science_future",
        "primary_color": "#d97706",   # Sunset Amber
        "bg_gradient": "linear-gradient(135deg, #451a03 0%, #78350f 50%, #b45309 100%)",
        "badge_bg": "#d97706",
    },
}

# ── Database ───────────────────────────────────────────────────────────────────
DB_FILE          = "database/published_topics.json"

# ── Trend sources (Multi-Horizon: 24h, Week, Month) ───────────────────────────
HN_TOP_STORIES_URL   = "https://hacker-news.firebaseio.com/v0/topstories.json"
HN_BEST_STORIES_URL  = "https://hacker-news.firebaseio.com/v0/beststories.json"
HN_ITEM_URL          = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HN_FETCH_COUNT       = 50

GOOGLE_TRENDS_RSS_URLS = [
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=US",
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=GB",
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=IN",
]

# Universal multi-horizon feeds covering Tech, Business, Science, and World
GLOBAL_HORIZON_FEEDS = {
    "24h": [
        "https://feeds.bbci.co.uk/news/technology/rss.xml",
        "https://feeds.bbci.co.uk/news/business/rss.xml",
        "https://feeds.arstechnica.com/arstechnica/index",
    ],
    "week": [
        "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
        "https://feeds.bbci.co.uk/news/world/rss.xml",
        "https://www.theverge.com/rss/index.xml",
    ],
    "month": [
        "https://feeds.bbci.co.uk/news/magazine/rss.xml",
        "https://feeds.bbci.co.uk/news/special_reports/rss.xml",
    ],
}

# ── Request settings ────────────────────────────────────────────────────────────
REQUEST_TIMEOUT  = 15
REQUEST_HEADERS  = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}
