"""
settings.py — Central configuration for AI Income Lab blog agent.
All sensitive values (API keys, blog ID) are loaded from environment
variables so they work both locally (.env file) and in GitHub Actions
(GitHub Secrets).
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── Gemini API ─────────────────────────────────────────────────────────────────
GEMINI_API_KEY   = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL     = "gemini-2.5-flash"
GEMINI_FALLBACK  = "gemini-2.0-flash"

# ── Blogger ────────────────────────────────────────────────────────────────────
BLOGGER_BLOG_ID  = os.getenv("BLOGGER_BLOG_ID", "")
BLOGGER_TOKEN_FILE = "token.json"           # generated by setup_auth.py

# ── Blog brand ─────────────────────────────────────────────────────────────────
BLOG_NAME        = "AI Income Lab"
BLOG_TAGLINE     = "Real ways to earn with AI. No hype."
BLOG_AUTHOR      = "AI Income Lab"

# ── Article generation ─────────────────────────────────────────────────────────
ARTICLES_PER_DAY = 3
MIN_WORD_COUNT   = 1200
MAX_WORD_COUNT   = 2000
GEMINI_TEMPERATURE = 0.75          # slightly creative but factual

# ── Database ───────────────────────────────────────────────────────────────────
DB_FILE          = "database/published_topics.json"

# ── Trend sources ──────────────────────────────────────────────────────────────
HN_TOP_STORIES_URL   = "https://hacker-news.firebaseio.com/v0/topstories.json"
HN_ITEM_URL          = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HN_FETCH_COUNT       = 40          # top N HN stories to inspect

GOOGLE_TRENDS_RSS_URLS = [
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=US",
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=GB",
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=IN",
]

REDDIT_RSS_FEEDS = [
    "https://www.reddit.com/r/personalfinance/top.rss?t=day",
    "https://www.reddit.com/r/ChatGPT/top.rss?t=day",
    "https://www.reddit.com/r/SideHustle/top.rss?t=day",
    "https://www.reddit.com/r/artificial/top.rss?t=day",
    "https://www.reddit.com/r/investing/top.rss?t=day",
    "https://www.reddit.com/r/Entrepreneur/top.rss?t=day",
]

# ── Request settings ────────────────────────────────────────────────────────────
REQUEST_TIMEOUT  = 15
REQUEST_HEADERS  = {
    "User-Agent": "Mozilla/5.0 (compatible; AIIncomeLabBot/1.0)"
}
