"""
settings.py — Central configuration for AI Income Lab blog agent.
All sensitive values (API keys, blog ID) are loaded from environment
variables so they work both locally (.env file) and in GitHub Actions
(GitHub Secrets).
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── Gemini API ─────────────────────────────────────────────────────────────────
GEMINI_API_KEY   = os.getenv("GEMINI_API_KEY", "")
GEMINI_MODEL     = "gemini-2.5-flash"
GEMINI_FALLBACK  = "gemini-2.0-flash"

# ── Blogger ────────────────────────────────────────────────────────────────────
BLOGGER_BLOG_ID  = os.getenv("BLOGGER_BLOG_ID", "")
BLOGGER_TOKEN_FILE = "token.json"           # generated by setup_auth.py

# ── Blog brand ─────────────────────────────────────────────────────────────────
BLOG_NAME        = "AI Income Lab"
BLOG_TAGLINE     = "Real ways to earn with AI. No hype."
BLOG_AUTHOR      = "AI Income Lab"

# ── Article generation & Staggered Schedule ──────────────────────────────────
# In automated mode, we run 3 times a day (Morning, Noon, Evening) with 1 article
# per run so publishing is spaced out naturally and never flagged as automated spam.
ARTICLES_PER_RUN = int(os.getenv("ARTICLES_COUNT", "1"))
MIN_WORD_COUNT   = 1200
MAX_WORD_COUNT   = 2000
GEMINI_TEMPERATURE = 0.75          # slightly creative but factual

# Slot Archetypes based on UTC time (IST = UTC + 5:30)
# Morning (03:30 UTC / 9:00 AM IST)  -> Market & Trend Breakdown
# Noon    (08:30 UTC / 2:00 PM IST)  -> Practical Masterclass & Tool Teardown
# Evening (14:30 UTC / 8:00 PM IST)  -> Case Study & Income Blueprint
SLOT_CONFIGS = {
    "morning": {
        "name": "Morning Signal & Market Analysis",
        "format": "market_breakdown",
        "niche_preference": "ai_finance_overlap",
        "primary_color": "#2563eb",   # Electric Cobalt Blue
        "bg_gradient": "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #1e3a8a 100%)",
        "badge_bg": "#2563eb",
    },
    "noon": {
        "name": "Midday Practical Masterclass",
        "format": "how_to",
        "niche_preference": "ai_tools",
        "primary_color": "#059669",   # Mint Emerald
        "bg_gradient": "linear-gradient(135deg, #064e3b 0%, #065f46 50%, #047857 100%)",
        "badge_bg": "#059669",
    },
    "evening": {
        "name": "Evening Playbook & Case Study",
        "format": "case_study",
        "niche_preference": "personal_finance",
        "primary_color": "#d97706",   # Sunset Amber
        "bg_gradient": "linear-gradient(135deg, #451a03 0%, #78350f 50%, #b45309 100%)",
        "badge_bg": "#d97706",
    },
}

# ── Database ───────────────────────────────────────────────────────────────────
DB_FILE          = "database/published_topics.json"

# ── Trend sources ──────────────────────────────────────────────────────────────
HN_TOP_STORIES_URL   = "https://hacker-news.firebaseio.com/v0/topstories.json"
HN_ITEM_URL          = "https://hacker-news.firebaseio.com/v0/item/{}.json"
HN_FETCH_COUNT       = 40          # top N HN stories to inspect

GOOGLE_TRENDS_RSS_URLS = [
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=US",
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=GB",
    "https://trends.google.com/trends/trendingsearches/daily/rss?geo=IN",
]

REDDIT_RSS_FEEDS = [
    "https://www.reddit.com/r/personalfinance/top.rss?t=day",
    "https://www.reddit.com/r/ChatGPT/top.rss?t=day",
    "https://www.reddit.com/r/SideHustle/top.rss?t=day",
    "https://www.reddit.com/r/artificial/top.rss?t=day",
    "https://www.reddit.com/r/investing/top.rss?t=day",
    "https://www.reddit.com/r/Entrepreneur/top.rss?t=day",
]

# ── Request settings ────────────────────────────────────────────────────────────
REQUEST_TIMEOUT  = 15
REQUEST_HEADERS  = {
    "User-Agent": "Mozilla/5.0 (compatible; AIIncomeLabBot/1.0)"
}
